---

- hosts: all
  become: true
  tasks:

  - name: install apache_package and php_package 
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }} "
      state: absent
      update_cache: yes
    
