---

- hosts: all
  become: true 
  pre_tasks:  
  - name: install updates
    tags: always    
    apt:
     
      upgrade: dist      
      update_cache: yes


- hosts: web_servers
  become: true
  tasks: 

  - name: install apache and php package
    tags: apache,apache2
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
  - name: copy a default html file for site
    tags: apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: yes
  tasks: 

  - name: install mariadb package
    tags: db,mariadb
    apt: 
      name: mariadb-server
      state: latest
    
           


 

